// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_page_ from "./routes/[page].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $noc_eng_3 from "./routes/noc-eng-3.tsx";
import * as $noc_eng_4 from "./routes/noc-eng-4.tsx";
import * as $noc_urdu_2 from "./routes/noc-urdu-2.tsx";
import * as $noc_urdu_3 from "./routes/noc-urdu-3.tsx";
import * as $noc_urdu_4 from "./routes/noc-urdu-4.tsx";
import * as $videos from "./routes/videos.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[page].tsx": $_page_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/noc-eng-3.tsx": $noc_eng_3,
    "./routes/noc-eng-4.tsx": $noc_eng_4,
    "./routes/noc-urdu-2.tsx": $noc_urdu_2,
    "./routes/noc-urdu-3.tsx": $noc_urdu_3,
    "./routes/noc-urdu-4.tsx": $noc_urdu_4,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/Footer.tsx": $Footer,
    "./islands/NavBar.tsx": $NavBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
